
// SVG;
export { default as bell } from './svg/bell.svg';
export { default as collapse } from './svg/collapse.svg';
export { default as dash } from './svg/dash.svg';
export { default as eicon } from './svg/eicon.svg';
export { default as fabrics } from './svg/fabrics.svg';
export { default as fold} from './svg/fold.svg';
export { default as inventory } from './svg/inventory.svg';
export { default as image1 } from './svg/image1.svg';
export { default as image2 } from './svg/image2.svg';
export { default as image3 } from './svg/image3.svg';
export { default as image4 } from './svg/image4.svg';
export { default as leftarrow } from './svg/leftarrow.svg';
export { default as line } from './svg/line.svg';
export { default as logo } from './svg/logo.svg';
export { default as message } from './svg/message.svg';
export { default as orders } from './svg/orders.svg';
export { default as rightarrow } from './svg/rightarrow.svg';
export { default as search } from './svg/search.svg';
export { default as settings } from './svg/settings.svg';
export { default as signout } from './svg/signout.svg';
export { default as side } from './svg/side.svg';
export { default as supply } from './svg/supply.svg';
export { default as tutorial } from './svg/tutorial.svg';
export { default as three } from './svg/three.svg';
export { default as user } from './svg/user.svg';
export { default as graph } from './svg/graph.svg';
export { default as table } from './svg/table.svg';
export { default as armchair } from './svg/armchair.svg';
export { default as bed } from './svg/bed.svg';
export { default as chair } from './svg/chair.svg';
export { default as mirror } from './svg/mirror.svg';
export { default as canvas } from './svg/canvas.svg';
export { default as shelf} from './svg/shelf.svg';